language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: {PUT_YOUR_OWN_API_KEY_HERE}
  app: sheltered-brook-11779
  on:
    repo: Jlin72/unittest-travis-heroku